name: Check Dockerfiles

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Find all student Dockerfiles
        run: |
          echo "Gefundene Dockerfiles:"
          find abgaben -name Dockerfile

      - name: Build each Dockerfile
        run: |
          for file in $(find abgaben -name Dockerfile); do
            echo "Baue: $file"
            dir=$(dirname $file)
            docker build -t testimage-$dir $dir || exit 1
          done
