name: Check all student Dockerfiles

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find all Dockerfiles
        run: |
          echo "Gefundene Dockerfiles:"
          find abgaben -name Dockerfile

      - name: Build each Dockerfile
        run: |
          for file in $(find abgaben -name Dockerfile); do
            echo "----------------------------------------"
            echo "Baue Dockerfile: $file"
            echo "----------------------------------------"
            dir=$(dirname $file)
            docker build -t testimage-$dir $dir || exit 1
          done
